#!/usr/bin/python3
def raise_exception():
    resutl = "hello" / 2
    return result
